# Generated by Django 2.2.6 on 2019-12-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191113_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth',
        ),
    ]
