# Generated by Django 2.2.6 on 2019-12-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Is Expired'),
        ),
    ]
