# Generated by Django 2.2.6 on 2020-01-29 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_emailverification_is_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindPasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name='UUID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_clear', models.BooleanField(default=False, verbose_name='성공 여부')),
                ('is_expired', models.BooleanField(default=False, verbose_name='만료 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '비밀번호 찾기 기록',
                'verbose_name_plural': '비밀번호 찾기 기록',
                'ordering': ['-id'],
            },
        ),
    ]
