# Generated by Django 2.2.6 on 2019-12-02 04:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Term Name')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Terms',
                'verbose_name_plural': 'Terms',
                'ordering': ['-id'],
            },
        ),
    ]
