# Generated by Django 2.2.6 on 2019-12-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Proposal Name')),
                ('file', models.FileField(upload_to='proposal/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposal',
                'ordering': ['-id'],
            },
        ),
    ]
