# Generated by Django 2.2.6 on 2019-11-05 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Nickname')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='studio/photographer/profile/', verbose_name='Profile Image')),
                ('main_location', models.CharField(max_length=255, verbose_name='Location')),
                ('education', models.CharField(max_length=255, verbose_name='Education')),
                ('career', models.CharField(max_length=255, verbose_name='Career')),
                ('studio_id', models.CharField(max_length=255, verbose_name='Studio ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photographer',
                'verbose_name_plural': 'Photographer',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='studio/photographer/portfolio/', verbose_name='Portfolio Image')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Photographer')),
            ],
            options={
                'verbose_name': 'Photographer Portfolio',
                'verbose_name_plural': 'Photographer Portfolio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Option Title')),
                ('photograpy_type', models.CharField(max_length=500, verbose_name='Photography Type')),
                ('description', models.TextField(verbose_name='Option Description')),
                ('person', models.PositiveIntegerField(verbose_name='How many people')),
                ('hour', models.FloatField(verbose_name='How many hours')),
                ('price', models.FloatField(verbose_name='How much in dollars')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Photographer')),
            ],
            options={
                'verbose_name': 'Photographer Option',
                'verbose_name_plural': 'Photographer Option',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Photographer')),
            ],
            options={
                'verbose_name': 'Photographer Location',
                'verbose_name_plural': 'Photographer Location',
                'ordering': ['-id'],
            },
        ),
    ]
