# Generated by Django 2.2.6 on 2019-11-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Portfolio URL'),
        ),
    ]
