# Generated by Django 2.2.6 on 2019-11-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_photographer_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='description',
            field=models.TextField(default='default', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
