# Generated by Django 2.2.6 on 2019-11-09 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('date_option', models.CharField(choices=[('Specific', 'Specific Date'), ('Range', 'Not Specific Date')], max_length=100, verbose_name='Date Option')),
                ('specific_date', models.DateTimeField(blank=True, null=True, verbose_name='Specific Date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Range Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Range End Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Location')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Option')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Photographer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Order',
                'verbose_name_plural': 'Customer Order',
                'ordering': ['-id'],
            },
        ),
    ]
