# Generated by Django 2.2.6 on 2019-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20191111_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=100, verbose_name='Order Status'),
        ),
    ]
