# Generated by Django 2.2.6 on 2019-11-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_auto_20191113_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available_time',
            field=models.TextField(blank=True, null=True, verbose_name='Available Time'),
        ),
    ]
