# Generated by Django 2.2.6 on 2019-11-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_order_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed Date'),
        ),
    ]
