# Generated by Django 2.2.6 on 2019-11-16 09:19

from django.db import migrations, models
import django.db.models.deletion
import prizm_server.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_order_confirmed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=prizm_server.common.utils.get_image_filename, verbose_name='Order Image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Order')),
            ],
            options={
                'verbose_name': 'Order Image',
                'verbose_name_plural': 'Order Image',
                'ordering': ['-id'],
            },
        ),
    ]
