# Generated by Django 2.2.6 on 2019-11-24 08:52

from django.db import migrations, models
import prizm_server.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_order_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=prizm_server.common.utils.get_image_filename, verbose_name='Compressed Order Image'),
        ),
    ]
