# Generated by Django 2.2.6 on 2019-11-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_orderimage_processed_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='processed_image',
        ),
    ]
