# Generated by Django 2.2.6 on 2019-11-25 11:58

from django.db import migrations
import imagekit.models.fields
import prizm_server.common.utils


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_remove_orderimage_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='processed_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=prizm_server.common.utils.get_processed_image_filename),
        ),
    ]
