# Generated by Django 2.2.6 on 2019-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_orderimage_processed_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotographerAccount',
        ),
    ]
