# Generated by Django 2.2.6 on 2019-12-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_delete_photographeraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=100, verbose_name='Order Status'),
        ),
    ]
