# Generated by Django 2.2.6 on 2019-12-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0022_auto_20191202_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Education'),
        ),
    ]
