# Generated by Django 2.2.6 on 2019-12-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0026_auto_20191220_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='location_option',
            field=models.CharField(choices=[('Specific', 'Specific Location'), ('Range', 'Not Specific Date')], default='Specific Location', max_length=100, verbose_name='Location Option'),
            preserve_default=False,
        ),
    ]
