# Generated by Django 2.2.6 on 2019-12-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0027_customrequest_location_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.Photographer'),
        ),
    ]
