# Generated by Django 2.2.6 on 2019-12-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0028_auto_20191222_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.Order'),
        ),
    ]
