# Generated by Django 2.2.6 on 2019-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0029_customrequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrequest',
            name='location_option',
            field=models.CharField(choices=[('Specific', 'Specific Location'), ('Range', 'Not Specific Location')], max_length=100, verbose_name='Location Option'),
        ),
    ]
