# Generated by Django 2.2.6 on 2019-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0032_requestorder_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorder',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Selected Location'),
        ),
    ]
