# Generated by Django 2.2.6 on 2019-12-23 16:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0033_auto_20191222_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=jsonfield.fields.JSONField(verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='option',
            field=jsonfield.fields.JSONField(verbose_name='Option'),
        ),
    ]
