# Generated by Django 2.2.6 on 2020-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0035_auto_20191229_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='portfolio_url',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='career',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Career'),
        ),
    ]
