from django.utils.translation import ugettext_lazy as _

COUNTRY_CODE = (
    ('AF', _('Afghanistan')),
    ('AX', _('Aland Islands')),
    ('AL', _('Albania')),
    ('DZ', _('Algeria')),
    ('AS', _('American Samoa')),
    ('AD', _('Andorra')),
    ('AO', _('Angola')),
    ('AI', _('Anguilla')),
    ('AQ', _('Antarctica')),
    ('AG', _('Antigua and Barbuda')),
    ('AR', _('Argentina')),
    ('AM', _('Armenia')),
    ('AW', _('Aruba')),
    ('AU', _('Australia')),
    ('AT', _('Austria')),
    ('AZ', _('Azerbaijan')),
    ('BS', _('Bahamas')),
    ('BH', _('Bahrain')),
    ('BD', _('Bangladesh')),
    ('BB', _('Barbados')),
    ('BY', _('Belarus')),
    ('BE', _('Belgium')),
    ('BZ', _('Belize')),
    ('BJ', _('Benin')),
    ('BM', _('Bermuda')),
    ('BT', _('Bhutan')),
    ('BO', _('Bolivia, Plurinational State of')),
    ('BA', _('Bosnia and Herzegovina')),
    ('BW', _('Botswana')),
    ('BR', _('Brazil')),
    ('IO', _('British Indian Ocean Territory')),
    ('BN', _('Brunei Darussalam')),
    ('BG', _('Bulgaria')),
    ('BF', _('Burkina Faso')),
    ('BI', _('Burundi')),
    ('KH', _('Cambodia')),
    ('CM', _('Cameroon')),
    ('CA', _('Canada')),
    ('CV', _('Cape Verde')),
    ('KY', _('Cayman Islands')),
    ('CF', _('Central African Republic')),
    ('TD', _('Chad')),
    ('CL', _('Chile')),
    ('CN', _('China')),
    ('CX', _('Christmas Island')),
    ('CC', _('Cocos Islands')),
    ('CO', _('Colombia')),
    ('KM', _('Comoros')),
    ('CG', _('Congo')),
    ('CD', _('Congo, the Democratic Republic of the')),
    ('CK', _('Cook Islands')),
    ('CR', _('Costa Rica')),
    ('CI', _("Cote d'Ivoire")),
    ('HR', _('Croatia')),
    ('CU', _('Cuba')),
    ('CW', _('Curacao')),
    ('CY', _('Cyprus')),
    ('CZ', _('Czech Republic')),
    ('DK', _('Denmark')),
    ('DJ', _('Djibouti')),
    ('DM', _('Dominica')),
    ('DO', _('Dominican Republic')),
    ('EC', _('Ecuador')),
    ('EG', _('Egypt')),
    ('SV', _('El Salvador')),
    ('GQ', _('Equatorial Guinea')),
    ('ER', _('Eritrea')),
    ('EE', _('Estonia')),
    ('ET', _('Ethiopia')),
    ('FK', _('Falkland Islands')),
    ('FO', _('Faroe Islands')),
    ('FJ', _('Fiji')),
    ('FI', _('Finland')),
    ('FR', _('France')),
    ('PF', _('French Polynesia')),
    ('GA', _('Gabon')),
    ('GM', _('Gambia')),
    ('GE', _('Georgia')),
    ('DE', _('Germany')),
    ('GH', _('Ghana')),
    ('GI', _('Gibraltar')),
    ('GR', _('Greece')),
    ('GL', _('Greenland')),
    ('GD', _('Grenada')),
    ('GP', _('Guadeloupe')),
    ('GU', _('Guam')),
    ('GT', _('Guatemala')),
    ('GG', _('Guernsey')),
    ('GN', _('Guinea')),
    ('GW', _('Guinea-Bissau')),
    ('GY', _('Guyana')),
    ('HT', _('Haiti')),
    ('VA', _('Holy See (Vatican City State)')),
    ('HN', _('Honduras')),
    ('HK', _('Hong Kong')),
    ('HU', _('Hungary')),
    ('IS', _('Iceland')),
    ('IN', _('India')),
    ('ID', _('Indonesia')),
    ('IR', _('Iran, Islamic Republic of')),
    ('IQ', _('Iraq')),
    ('IE', _('Ireland')),
    ('IM', _('Isle of Man')),
    ('IL', _('Israel')),
    ('IT', _('Italy')),
    ('JM', _('Jamaica')),
    ('JP', _('Japan')),
    ('JE', _('Jersey')),
    ('JO', _('Jordan')),
    ('KZ', _('Kazakhstan')),
    ('KE', _('Kenya')),
    ('KI', _('Kiribati')),
    ('KP', _("Korea, Democratic People's Republic of")),
    ('KR', _('Korea, Republic of')),
    ('KW', _('Kuwait')),
    ('KG', _('Kyrgyzstan')),
    ('LA', _("LAOS")),
    ('LV', _('Latvia')),
    ('LB', _('Lebanon')),
    ('LS', _('Lesotho')),
    ('LR', _('Liberia')),
    ('LY', _('Libya')),
    ('LI', _('Liechtenstein')),
    ('LT', _('Lithuania')),
    ('LU', _('Luxembourg')),
    ('MO', _('Macao')),
    ('MK', _('Macedonia')),
    ('MG', _('Madagascar')),
    ('MW', _('Malawi')),
    ('MY', _('Malaysia')),
    ('MV', _('Maldives')),
    ('ML', _('Mali')),
    ('MT', _('Malta')),
    ('MH', _('Marshall Islands')),
    ('MQ', _('Martinique')),
    ('MR', _('Mauritania')),
    ('MU', _('Mauritius')),
    ('YT', _('Mayotte')),
    ('MX', _('Mexico')),
    ('FM', _('Micronesia, Federated States of')),
    ('MD', _('Moldova, Republic of')),
    ('MC', _('Monaco')),
    ('MN', _('Mongolia')),
    ('ME', _('Montenegro')),
    ('MS', _('Montserrat')),
    ('MA', _('Morocco')),
    ('MZ', _('Mozambique')),
    ('MM', _('Myanmar')),
    ('NA', _('Namibia')),
    ('NR', _('Nauru')),
    ('NP', _('Nepal')),
    ('NL', _('Netherlands')),
    ('NC', _('New Caledonia')),
    ('NZ', _('New Zealand')),
    ('NI', _('Nicaragua')),
    ('NE', _('Niger')),
    ('NG', _('Nigeria')),
    ('NU', _('Niue')),
    ('NF', _('Norfolk Island')),
    ('MP', _('Northern Mariana Islands')),
    ('NO', _('Norway')),
    ('OM', _('Oman')),
    ('PK', _('Pakistan')),
    ('PW', _('Palau')),
    ('PS', _('Palestine, State of')),
    ('PA', _('Panama')),
    ('PG', _('Papua New Guinea')),
    ('PY', _('Paraguay')),
    ('PE', _('Peru')),
    ('PH', _('Philippines')),
    ('PN', _('Pitcairn')),
    ('PL', _('Poland')),
    ('PT', _('Portugal')),
    ('PR', _('Puerto Rico')),
    ('QA', _('Qatar')),
    ('RE', _('Reunion')),
    ('RO', _('Romania')),
    ('RU', _('Russia')),
    ('RW', _('Rwanda')),
    ('BL', _('Saint Barthelemy')),
    ('SH', _('Saint Helena, Ascension and Tristan da Cunha')),
    ('KN', _('Saint Kitts and Nevis')),
    ('LC', _('Saint Lucia')),
    ('MF', _('Saint Martin')),
    ('PM', _('Saint Pierre and Miquelon')),
    ('VC', _('Saint Vincent and the Grenadines')),
    ('WS', _('Samoa')),
    ('SM', _('San Marino')),
    ('ST', _('Sao Tome and Principe')),
    ('SA', _('Saudi Arabia')),
    ('SN', _('Senegal')),
    ('RS', _('Serbia')),
    ('SC', _('Seychelles')),
    ('SL', _('Sierra Leone')),
    ('SG', _('Singapore')),
    ('SX', _('Sint Maarten')),
    ('SK', _('Slovakia')),
    ('SI', _('Slovenia')),
    ('SB', _('Solomon Islands')),
    ('SO', _('Somalia')),
    ('ZA', _('South Africa')),
    ('GS', _('South Georgia and the South Sandwich Islands')),
    ('SS', _('South Sudan')),
    ('ES', _('Spain')),
    ('LK', _('Sri Lanka')),
    ('SD', _('Sudan')),
    ('SR', _('Suriname')),
    ('SJ', _('Svalbard and Jan Mayen')),
    ('SZ', _('Swaziland')),
    ('SE', _('Sweden')),
    ('CH', _('Switzerland')),
    ('SY', _('Syrian Arab Republic')),
    ('TW', _('Taiwan, Province of China')),
    ('TJ', _('Tajikistan')),
    ('TZ', _('Tanzania, United Republic of')),
    ('TH', _('Thailand')),
    ('TL', _('Timor-Leste')),
    ('TG', _('Togo')),
    ('TK', _('Tokelau')),
    ('TO', _('Tonga')),
    ('TT', _('Trinidad and Tobago')),
    ('TN', _('Tunisia')),
    ('TR', _('Turkey')),
    ('TM', _('Turkmenistan')),
    ('TC', _('Turks and Caicos Islands')),
    ('TV', _('Tuvalu')),
    ('UG', _('Uganda')),
    ('UA', _('Ukraine')),
    ('AE', _('United Arab Emirates')),
    ('GB', _('United Kingdom')),
    ('US', _('United States')),
    ('UM', _('United States Minor Outlying Islands')),
    ('UY', _('Uruguay')),
    ('UZ', _('Uzbekistan')),
    ('VU', _('Vanuatu')),
    ('VE', _('Venezuela, Bolivarian Republic of')),
    ('VN', _('Vietnam')),
    ('VG', _('Virgin Islands, British')),
    ('VI', _('Virgin Islands, U.S.')),
    ('WF', _('Wallis and Futuna')),
    ('EH', _('Western Sahara')),
    ('YE', _('Yemen')),
    ('ZM', _('Zambia')),
    ('ZW', _('Zimbabwe')),
)

COUNTRY_NUMBER = (
    ('93', _('Afghanistan')),
    ('358', _('Aland Islands')),
    ('355', _('Albania')),
    ('213', _('Algeria')),
    ('1-684', _('American Samoa')),
    ('376', _('Andorra')),
    ('244', _('Angola')),
    ('1-264', _('Anguilla')),
    ('672', _('Antarctica')),
    ('1-268', _('Antigua and Barbuda')),
    ('54', _('Argentina')),
    ('374', _('Armenia')),
    ('297', _('Aruba')),
    ('61', _('Australia')),
    ('43', _('Austria')),
    ('994', _('Azerbaijan')),
    ('1-242', _('Bahamas')),
    ('973', _('Bahrain')),
    ('880', _('Bangladesh')),
    ('1-246', _('Barbados')),
    ('375', _('Belarus')),
    ('32', _('Belgium')),
    ('501', _('Belize')),
    ('229', _('Benin')),
    ('1-441', _('Bermuda')),
    ('975', _('Bhutan')),
    ('591', _('Bolivia, Plurinational State of')),
    ('387', _('Bosnia and Herzegovina')),
    ('267', _('Botswana')),
    ('55', _('Brazil')),
    ('246', _('British Indian Ocean Territory')),
    ('673', _('Brunei Darussalam')),
    ('359', _('Bulgaria')),
    ('226', _('Burkina Faso')),
    ('257', _('Burundi')),
    ('855', _('Cambodia')),
    ('237', _('Cameroon')),
    ('1', _('Canada')),
    ('238', _('Cape Verde')),
    ('1-345', _('Cayman Islands')),
    ('236', _('Central African Republic')),
    ('235', _('Chad')),
    ('56', _('Chile')),
    ('86', _('China')),
    ('61', _('Christmas Island')),
    ('61', _('Cocos Islands')),
    ('57', _('Colombia')),
    ('269', _('Comoros')),
    ('242', _('Congo')),
    ('243', _('Congo, the Democratic Republic of the')),
    ('682', _('Cook Islands')),
    ('506', _('Costa Rica')),
    ('225', _("Cote d'Ivoire")),
    ('385', _('Croatia')),
    ('53', _('Cuba')),
    ('599', _('Curacao')),
    ('357', _('Cyprus')),
    ('420', _('Czech Republic')),
    ('45', _('Denmark')),
    ('253', _('Djibouti')),
    ('1-767', _('Dominica')),
    ('809', _('Dominican Republic')),
    ('593', _('Ecuador')),
    ('20', _('Egypt')),
    ('503', _('El Salvador')),
    ('240', _('Equatorial Guinea')),
    ('291', _('Eritrea')),
    ('372', _('Estonia')),
    ('251', _('Ethiopia')),
    ('500', _('Falkland Islands')),
    ('298', _('Faroe Islands')),
    ('679', _('Fiji')),
    ('358', _('Finland')),
    ('33', _('France')),
    ('689', _('French Polynesia')),
    ('241', _('Gabon')),
    ('220', _('Gambia')),
    ('995', _('Georgia')),
    ('49', _('Germany')),
    ('233', _('Ghana')),
    ('350', _('Gibraltar')),
    ('30', _('Greece')),
    ('299', _('Greenland')),
    ('1-473', _('Grenada')),
    ('590', _('Guadeloupe')),
    ('1-671', _('Guam')),
    ('502', _('Guatemala')),
    ('44-1481', _('Guernsey')),
    ('224', _('Guinea')),
    ('245', _('Guinea-Bissau')),
    ('592', _('Guyana')),
    ('509', _('Haiti')),
    ('379', _('Holy See (Vatican City State)')),
    ('504', _('Honduras')),
    ('852', _('Hong Kong')),
    ('36', _('Hungary')),
    ('354', _('Iceland')),
    ('91', _('India')),
    ('62', _('Indonesia')),
    ('98', _('Iran, Islamic Republic of')),
    ('964', _('Iraq')),
    ('353', _('Ireland')),
    ('44-1624', _('Isle of Man')),
    ('972', _('Israel')),
    ('39', _('Italy')),
    ('1-876', _('Jamaica')),
    ('81', _('Japan')),
    ('44-1534', _('Jersey')),
    ('962', _('Jordan')),
    ('7', _('Kazakhstan')),
    ('254', _('Kenya')),
    ('686', _('Kiribati')),
    ('850', _("Korea, Democratic People's Republic of")),
    ('82', _('Korea, Republic of')),
    ('965', _('Kuwait')),
    ('996', _('Kyrgyzstan')),
    ('856', _("LAOS")),
    ('371', _('Latvia')),
    ('961', _('Lebanon')),
    ('266', _('Lesotho')),
    ('231', _('Liberia')),
    ('218', _('Libya')),
    ('423', _('Liechtenstein')),
    ('370', _('Lithuania')),
    ('352', _('Luxembourg')),
    ('853', _('Macao')),
    ('389', _('Macedonia')),
    ('261', _('Madagascar')),
    ('265', _('Malawi')),
    ('60', _('Malaysia')),
    ('960', _('Maldives')),
    ('223', _('Mali')),
    ('356', _('Malta')),
    ('692', _('Marshall Islands')),
    ('596', _('Martinique')),
    ('222', _('Mauritania')),
    ('230', _('Mauritius')),
    ('262', _('Mayotte')),
    ('52', _('Mexico')),
    ('691', _('Micronesia, Federated States of')),
    ('373', _('Moldova, Republic of')),
    ('377', _('Monaco')),
    ('976', _('Mongolia')),
    ('382', _('Montenegro')),
    ('1-664', _('Montserrat')),
    ('212', _('Morocco')),
    ('258', _('Mozambique')),
    ('95', _('Myanmar')),
    ('264', _('Namibia')),
    ('674', _('Nauru')),
    ('977', _('Nepal')),
    ('31', _('Netherlands')),
    ('687', _('New Caledonia')),
    ('64', _('New Zealand')),
    ('505', _('Nicaragua')),
    ('227', _('Niger')),
    ('234', _('Nigeria')),
    ('683', _('Niue')),
    ('672', _('Norfolk Island')),
    ('1-670', _('Northern Mariana Islands')),
    ('47', _('Norway')),
    ('968', _('Oman')),
    ('92', _('Pakistan')),
    ('680', _('Palau')),
    ('670', _('Palestine, State of')),
    ('507', _('Panama')),
    ('675', _('Papua New Guinea')),
    ('595', _('Paraguay')),
    ('51', _('Peru')),
    ('63', _('Philippines')),
    ('64', _('Pitcairn')),
    ('48', _('Poland')),
    ('351', _('Portugal')),
    ('1-787', _('Puerto Rico')),
    ('974', _('Qatar')),
    ('262', _('Reunion')),
    ('40', _('Romania')),
    ('7', _('Russia')),
    ('250', _('Rwanda')),
    ('590', _('Saint Barthelemy')),
    ('290', _('Saint Helena, Ascension and Tristan da Cunha')),
    ('1-869', _('Saint Kitts and Nevis')),
    ('1-758', _('Saint Lucia')),
    ('590', _('Saint Martin')),
    ('508', _('Saint Pierre and Miquelon')),
    ('1-784', _('Saint Vincent and the Grenadines')),
    ('685', _('Samoa')),
    ('378', _('San Marino')),
    ('239', _('Sao Tome and Principe')),
    ('966', _('Saudi Arabia')),
    ('221', _('Senegal')),
    ('381', _('Serbia')),
    ('248', _('Seychelles')),
    ('232', _('Sierra Leone')),
    ('65', _('Singapore')),
    ('1-721', _('Sint Maarten')),
    ('421', _('Slovakia')),
    ('386', _('Slovenia')),
    ('677', _('Solomon Islands')),
    ('252', _('Somalia')),
    ('27', _('South Africa')),
    ('500', _('South Georgia and the South Sandwich Islands')),
    ('211', _('South Sudan')),
    ('34', _('Spain')),
    ('94', _('Sri Lanka')),
    ('249', _('Sudan')),
    ('597', _('Suriname')),
    ('47', _('Svalbard and Jan Mayen')),
    ('268', _('Swaziland')),
    ('46', _('Sweden')),
    ('41', _('Switzerland')),
    ('963', _('Syrian Arab Republic')),
    ('886', _('Taiwan, Province of China')),
    ('992', _('Tajikistan')),
    ('255', _('Tanzania, United Republic of')),
    ('66', _('Thailand')),
    ('670', _('Timor-Leste')),
    ('228', _('Togo')),
    ('690', _('Tokelau')),
    ('676', _('Tonga')),
    ('1-868', _('Trinidad and Tobago')),
    ('216', _('Tunisia')),
    ('90', _('Turkey')),
    ('993', _('Turkmenistan')),
    ('1-649', _('Turks and Caicos Islands')),
    ('688', _('Tuvalu')),
    ('256', _('Uganda')),
    ('380', _('Ukraine')),
    ('971', _('United Arab Emirates')),
    ('44', _('United Kingdom')),
    ('1', _('United States')),
    ('246', _('United States Minor Outlying Islands')),
    ('598', _('Uruguay')),
    ('998', _('Uzbekistan')),
    ('678', _('Vanuatu')),
    ('58', _('Venezuela, Bolivarian Republic of')),
    ('84', _('Vietnam')),
    ('1284', _('Virgin Islands, British')),
    ('1', _('Virgin Islands, U.S.')),
    ('681', _('Wallis and Futuna')),
    ('212', _('Western Sahara')),
    ('967', _('Yemen')),
    ('260', _('Zambia')),
    ('263', _('Zimbabwe')),
)

LANGUAGES = (
    ('ab', 'Abkhaz',),
    ('aa', 'Afar',),
    ('af', 'Afrikaans',),
    ('ak', 'Akan',),
    ('sq', 'Albanian',),
    ('am', 'Amharic',),
    ('ar', 'Arabic',),
    ('an', 'Aragonese',),
    ('hy', 'Armenian',),
    ('as', 'Assamese',),
    ('av', 'Avaric',),
    ('ae', 'Avestan',),
    ('ay', 'Aymara',),
    ('az', 'Azerbaijani',),
    ('bm', 'Bambara',),
    ('ba', 'Bashkir',),
    ('eu', 'Basque',),
    ('be', 'Belarusian',),
    ('bn', 'Bengali',),
    ('bh', 'Bihari',),
    ('bi', 'Bislama',),
    ('bs', 'Bosnian',),
    ('br', 'Breton',),
    ('bg', 'Bulgarian',),
    ('my', 'Burmese',),
    ('ca', 'Catalan',),
    ('ch', 'Chamorro',),
    ('ce', 'Chechen',),
    ('ny', 'Chichewa',),
    ('zh', 'Chinese',),
    ('cv', 'Chuvash',),
    ('kw', 'Cornish',),
    ('co', 'Corsican',),
    ('cr', 'Cree',),
    ('hr', 'Croatian',),
    ('cs', 'Czech',),
    ('da', 'Danish',),
    ('dv', 'Divehi',),
    ('nl', 'Dutch',),
    ('dz', 'Dzongkha',),
    ('en', 'English',),
    ('eo', 'Esperanto',),
    ('et', 'Estonian',),
    ('ee', 'Ewe',),
    ('fo', 'Faroese',),
    ('fj', 'Fijian',),
    ('fi', 'Finnish',),
    ('fr', 'French',),
    ('ff', 'Fula',),
    ('gl', 'Galician',),
    ('ka', 'Georgian',),
    ('de', 'German',),
    ('el', 'Greek',),
    ('gn', 'Guaran\xc3\xad',),
    ('gu', 'Gujarati',),
    ('ht', 'Haitian',),
    ('ha', 'Hausa',),
    ('he', 'Hebrew',),
    ('hz', 'Herero',),
    ('hi', 'Hindi',),
    ('ho', 'Hiri Motu',),
    ('hu', 'Hungarian',),
    ('ia', 'Interlingua',),
    ('id', 'Indonesian',),
    ('ie', 'Interlingue',),
    ('ga', 'Irish',),
    ('ig', 'Igbo',),
    ('ik', 'Inupiaq',),
    ('io', 'Ido',),
    ('is', 'Icelandic',),
    ('it', 'Italian',),
    ('iu', 'Inuktitut',),
    ('ja', 'Japanese',),
    ('jv', 'Javanese',),
    ('kl', 'Kalaallisut',),
    ('kn', 'Kannada',),
    ('kr', 'Kanuri',),
    ('ks', 'Kashmiri',),
    ('kk', 'Kazakh',),
    ('km', 'Khmer',),
    ('ki', 'Kikuyu',),
    ('rw', 'Kinyarwanda',),
    ('ky', 'Kyrgyz',),
    ('kv', 'Komi',),
    ('kg', 'Kongo',),
    ('ko', 'Korean',),
    ('ku', 'Kurdish',),
    ('kj', 'Kwanyama',),
    ('la', 'Latin',),
    ('lb', 'Luxembourgish',),
    ('lg', 'Ganda',),
    ('li', 'Limburgish',),
    ('ln', 'Lingala',),
    ('lo', 'Lao',),
    ('lt', 'Lithuanian',),
    ('lu', 'Luba-Katanga',),
    ('lv', 'Latvian',),
    ('gv', 'Manx',),
    ('mk', 'Macedonian',),
    ('mg', 'Malagasy',),
    ('ms', 'Malay',),
    ('ml', 'Malayalam',),
    ('mt', 'Maltese',),
    ('mi', 'M\xc4\x81ori',),
    ('mr', 'Marathi (Mar\xc4\x81\xe1\xb9\xadh\xc4\xab)',),
    ('mh', 'Marshallese',),
    ('mn', 'Mongolian',),
    ('na', 'Nauru',),
    ('nv', 'Navajo',),
    ('nb', 'Norwegian Bokm\xc3\xa5l',),
    ('nd', 'North Ndebele',),
    ('ne', 'Nepali',),
    ('ng', 'Ndonga',),
    ('nn', 'Norwegian Nynorsk',),
    ('no', 'Norwegian',),
    ('ii', 'Nuosu',),
    ('nr', 'South Ndebele',),
    ('oc', 'Occitan',),
    ('oj', 'Ojibwe',),
    ('cu', 'Old Church Slavonic',),
    ('om', 'Oromo',),
    ('or', 'Oriya',),
    ('os', 'Ossetian',),
    ('pa', 'Panjabi',),
    ('pi', 'P\xc4\x81li',),
    ('fa', 'Persian',),
    ('pl', 'Polish',),
    ('ps', 'Pashto',),
    ('pt', 'Portuguese',),
    ('qu', 'Quechua',),
    ('rm', 'Romansh',),
    ('rn', 'Kirundi',),
    ('ro', 'Romanian',),
    ('ru', 'Russian',),
    ('sa', 'Sanskrit (Sa\xe1\xb9\x81sk\xe1\xb9\x9bta)',),
    ('sc', 'Sardinian',),
    ('sd', 'Sindhi',),
    ('se', 'Northern Sami',),
    ('sm', 'Samoan',),
    ('sg', 'Sango',),
    ('sr', 'Serbian',),
    ('gd', 'Scottish Gaelic',),
    ('sn', 'Shona',),
    ('si', 'Sinhala',),
    ('sk', 'Slovak',),
    ('sl', 'Slovene',),
    ('so', 'Somali',),
    ('st', 'Southern Sotho',),
    ('az', 'South Azerbaijani',),
    ('es', 'Spanish',),
    ('su', 'Sundanese',),
    ('sw', 'Swahili',),
    ('ss', 'Swati',),
    ('sv', 'Swedish',),
    ('ta', 'Tamil',),
    ('te', 'Telugu',),
    ('tg', 'Tajik',),
    ('th', 'Thai',),
    ('ti', 'Tigrinya',),
    ('bo', 'Tibetan Standard',),
    ('tk', 'Turkmen',),
    ('tl', 'Tagalog',),
    ('tn', 'Tswana',),
    ('to', 'Tonga',),
    ('tr', 'Turkish',),
    ('ts', 'Tsonga',),
    ('tt', 'Tatar',),
    ('tw', 'Twi',),
    ('ty', 'Tahitian',),
    ('ug', 'Uyghur',),
    ('uk', 'Ukrainian',),
    ('ur', 'Urdu',),
    ('uz', 'Uzbek',),
    ('ve', 'Venda',),
    ('vi', 'Vietnamese',),
    ('vo', 'Volap\xc3\xbck',),
    ('wa', 'Walloon',),
    ('cy', 'Welsh',),
    ('wo', 'Wolof',),
    ('fy', 'Western Frisian',),
    ('xh', 'Xhosa',),
    ('yi', 'Yiddish',),
    ('yo', 'Yoruba',),
    ('za', 'Zhuang',),
    ('zu', 'Zulu',),
)