const COUNTRY_NUMBER = [
    {value: '93', label: 'Afghanistan'},
    {value: '358', label: 'Aland Islands'},
    {value: '355', label: 'Albania'},
    {value: '213', label: 'Algeria'},
    {value: '1-684', label: 'American Samoa'},
    {value: '376', label: 'Andorra'},
    {value: '244', label: 'Angola'},
    {value: '1-264', label: 'Anguilla'},
    {value: '672', label: 'Antarctica'},
    {value: '1-268', label: 'Antigua and Barbuda'},
    {value: '54', label: 'Argentina'},
    {value: '374', label: 'Armenia'},
    {value: '297', label: 'Aruba'},
    {value: '61', label: 'Australia'},
    {value: '43', label: 'Austria'},
    {value: '994', label: 'Azerbaijan'},
    {value: '1-242', label: 'Bahamas'},
    {value: '973', label: 'Bahrain'},
    {value: '880', label: 'Bangladesh'},
    {value: '1-246', label: 'Barbados'},
    {value: '375', label: 'Belarus'},
    {value: '32', label: 'Belgium'},
    {value: '501', label: 'Belize'},
    {value: '229', label: 'Benin'},
    {value: '1-441', label: 'Bermuda'},
    {value: '975', label: 'Bhutan'},
    {value: '591', label: 'Bolivia, Plurinational State of'},
    {value: '387', label: 'Bosnia and Herzegovina'},
    {value: '267', label: 'Botswana'},
    {value: '55', label: 'Brazil'},
    {value: '246', label: 'British Indian Ocean Territory'},
    {value: '673', label: 'Brunei Darussalam'},
    {value: '359', label: 'Bulgaria'},
    {value: '226', label: 'Burkina Faso'},
    {value: '257', label: 'Burundi'},
    {value: '855', label: 'Cambodia'},
    {value: '237', label: 'Cameroon'},
    {value: '1', label: 'Canada'},
    {value: '238', label: 'Cape Verde'},
    {value: '1-345', label: 'Cayman Islands'},
    {value: '236', label: 'Central African Republic'},
    {value: '235', label: 'Chad'},
    {value: '56', label: 'Chile'},
    {value: '86', label: 'China'},
    {value: '61', label: 'Christmas Island'},
    {value: '61', label: 'Cocos Islands'},
    {value: '57', label: 'Colombia'},
    {value: '269', label: 'Comoros'},
    {value: '242', label: 'Congo'},
    {value: '243', label: 'Congo, the Democratic Republic of the'},
    {value: '682', label: 'Cook Islands'},
    {value: '506', label: 'Costa Rica'},
    {value: '225', label: "Cote d'Ivoire"},
    {value: '385', label: 'Croatia'},
    {value: '53', label: 'Cuba'},
    {value: '599', label: 'Curacao'},
    {value: '357', label: 'Cyprus'},
    {value: '420', label: 'Czech Republic'},
    {value: '45', label: 'Denmark'},
    {value: '253', label: 'Djibouti'},
    {value: '1-767', label: 'Dominica'},
    {value: '809', label: 'Dominican Republic'},
    {value: '593', label: 'Ecuador'},
    {value: '20', label: 'Egypt'},
    {value: '503', label: 'El Salvador'},
    {value: '240', label: 'Equatorial Guinea'},
    {value: '291', label: 'Eritrea'},
    {value: '372', label: 'Estonia'},
    {value: '251', label: 'Ethiopia'},
    {value: '500', label: 'Falkland Islands'},
    {value: '298', label: 'Faroe Islands'},
    {value: '679', label: 'Fiji'},
    {value: '358', label: 'Finland'},
    {value: '33', label: 'France'},
    {value: '689', label: 'French Polynesia'},
    {value: '241', label: 'Gabon'},
    {value: '220', label: 'Gambia'},
    {value: '995', label: 'Georgia'},
    {value: '49', label: 'Germany'},
    {value: '233', label: 'Ghana'},
    {value: '350', label: 'Gibraltar'},
    {value: '30', label: 'Greece'},
    {value: '299', label: 'Greenland'},
    {value: '1-473', label: 'Grenada'},
    {value: '590', label: 'Guadeloupe'},
    {value: '1-671', label: 'Guam'},
    {value: '502', label: 'Guatemala'},
    {value: '44-1481', label: 'Guernsey'},
    {value: '224', label: 'Guinea'},
    {value: '245', label: 'Guinea-Bissau'},
    {value: '592', label: 'Guyana'},
    {value: '509', label: 'Haiti'},
    {value: '379', label: 'Holy See {value: Vatican City State)'},
    {value: '504', label: 'Honduras'},
    {value: '852', label: 'Hong Kong'},
    {value: '36', label: 'Hungary'},
    {value: '354', label: 'Iceland'},
    {value: '91', label: 'India'},
    {value: '62', label: 'Indonesia'},
    {value: '98', label: 'Iran, Islamic Republic of'},
    {value: '964', label: 'Iraq'},
    {value: '353', label: 'Ireland'},
    {value: '44-1624', label: 'Isle of Man'},
    {value: '972', label: 'Israel'},
    {value: '39', label: 'Italy'},
    {value: '1-876', label: 'Jamaica'},
    {value: '81', label: 'Japan'},
    {value: '44-1534', label: 'Jersey'},
    {value: '962', label: 'Jordan'},
    {value: '7', label: 'Kazakhstan'},
    {value: '254', label: 'Kenya'},
    {value: '686', label: 'Kiribati'},
    {value: '850', label: "Korea, Democratic People's Republic of"},
    {value: '82', label: 'Korea, Republic of'},
    {value: '965', label: 'Kuwait'},
    {value: '996', label: 'Kyrgyzstan'},
    {value: '856', label: "LAOS"},
    {value: '371', label: 'Latvia'},
    {value: '961', label: 'Lebanon'},
    {value: '266', label: 'Lesotho'},
    {value: '231', label: 'Liberia'},
    {value: '218', label: 'Libya'},
    {value: '423', label: 'Liechtenstein'},
    {value: '370', label: 'Lithuania'},
    {value: '352', label: 'Luxembourg'},
    {value: '853', label: 'Macao'},
    {value: '389', label: 'Macedonia'},
    {value: '261', label: 'Madagascar'},
    {value: '265', label: 'Malawi'},
    {value: '60', label: 'Malaysia'},
    {value: '960', label: 'Maldives'},
    {value: '223', label: 'Mali'},
    {value: '356', label: 'Malta'},
    {value: '692', label: 'Marshall Islands'},
    {value: '596', label: 'Martinique'},
    {value: '222', label: 'Mauritania'},
    {value: '230', label: 'Mauritius'},
    {value: '262', label: 'Mayotte'},
    {value: '52', label: 'Mexico'},
    {value: '691', label: 'Micronesia, Federated States of'},
    {value: '373', label: 'Moldova, Republic of'},
    {value: '377', label: 'Monaco'},
    {value: '976', label: 'Mongolia'},
    {value: '382', label: 'Montenegro'},
    {value: '1-664', label: 'Montserrat'},
    {value: '212', label: 'Morocco'},
    {value: '258', label: 'Mozambique'},
    {value: '95', label: 'Myanmar'},
    {value: '264', label: 'Namibia'},
    {value: '674', label: 'Nauru'},
    {value: '977', label: 'Nepal'},
    {value: '31', label: 'Netherlands'},
    {value: '687', label: 'New Caledonia'},
    {value: '64', label: 'New Zealand'},
    {value: '505', label: 'Nicaragua'},
    {value: '227', label: 'Niger'},
    {value: '234', label: 'Nigeria'},
    {value: '683', label: 'Niue'},
    {value: '672', label: 'Norfolk Island'},
    {value: '1-670', label: 'Northern Mariana Islands'},
    {value: '47', label: 'Norway'},
    {value: '968', label: 'Oman'},
    {value: '92', label: 'Pakistan'},
    {value: '680', label: 'Palau'},
    {value: '670', label: 'Palestine, State of'},
    {value: '507', label: 'Panama'},
    {value: '675', label: 'Papua New Guinea'},
    {value: '595', label: 'Paraguay'},
    {value: '51', label: 'Peru'},
    {value: '63', label: 'Philippines'},
    {value: '64', label: 'Pitcairn'},
    {value: '48', label: 'Poland'},
    {value: '351', label: 'Portugal'},
    {value: '1-787', label: 'Puerto Rico'},
    {value: '974', label: 'Qatar'},
    {value: '262', label: 'Reunion'},
    {value: '40', label: 'Romania'},
    {value: '7', label: 'Russia'},
    {value: '250', label: 'Rwanda'},
    {value: '590', label: 'Saint Barthelemy'},
    {value: '290', label: 'Saint Helena, Ascension and Tristan da Cunha'},
    {value: '1-869', label: 'Saint Kitts and Nevis'},
    {value: '1-758', label: 'Saint Lucia'},
    {value: '590', label: 'Saint Martin'},
    {value: '508', label: 'Saint Pierre and Miquelon'},
    {value: '1-784', label: 'Saint Vincent and the Grenadines'},
    {value: '685', label: 'Samoa'},
    {value: '378', label: 'San Marino'},
    {value: '239', label: 'Sao Tome and Principe'},
    {value: '966', label: 'Saudi Arabia'},
    {value: '221', label: 'Senegal'},
    {value: '381', label: 'Serbia'},
    {value: '248', label: 'Seychelles'},
    {value: '232', label: 'Sierra Leone'},
    {value: '65', label: 'Singapore'},
    {value: '1-721', label: 'Sint Maarten'},
    {value: '421', label: 'Slovakia'},
    {value: '386', label: 'Slovenia'},
    {value: '677', label: 'Solomon Islands'},
    {value: '252', label: 'Somalia'},
    {value: '27', label: 'South Africa'},
    {value: '500', label: 'South Georgia and the South Sandwich Islands'},
    {value: '211', label: 'South Sudan'},
    {value: '34', label: 'Spain'},
    {value: '94', label: 'Sri Lanka'},
    {value: '249', label: 'Sudan'},
    {value: '597', label: 'Suriname'},
    {value: '47', label: 'Svalbard and Jan Mayen'},
    {value: '268', label: 'Swaziland'},
    {value: '46', label: 'Sweden'},
    {value: '41', label: 'Switzerland'},
    {value: '963', label: 'Syrian Arab Republic'},
    {value: '886', label: 'Taiwan, Province of China'},
    {value: '992', label: 'Tajikistan'},
    {value: '255', label: 'Tanzania, United Republic of'},
    {value: '66', label: 'Thailand'},
    {value: '670', label: 'Timor-Leste'},
    {value: '228', label: 'Togo'},
    {value: '690', label: 'Tokelau'},
    {value: '676', label: 'Tonga'},
    {value: '1-868', label: 'Trinidad and Tobago'},
    {value: '216', label: 'Tunisia'},
    {value: '90', label: 'Turkey'},
    {value: '993', label: 'Turkmenistan'},
    {value: '1-649', label: 'Turks and Caicos Islands'},
    {value: '688', label: 'Tuvalu'},
    {value: '256', label: 'Uganda'},
    {value: '380', label: 'Ukraine'},
    {value: '971', label: 'United Arab Emirates'},
    {value: '44', label: 'United Kingdom'},
    {value: '1', label: 'United States'},
    {value: '246', label: 'United States Minor Outlying Islands'},
    {value: '598', label: 'Uruguay'},
    {value: '998', label: 'Uzbekistan'},
    {value: '678', label: 'Vanuatu'},
    {value: '58', label: 'Venezuela, Bolivarian Republic of'},
    {value: '84', label: 'Vietnam'},
    {value: '1284', label: 'Virgin Islands, British'},
    {value: '1', label: 'Virgin Islands, U.S.'},
    {value: '681', label: 'Wallis and Futuna'},
    {value: '212', label: 'Western Sahara'},
    {value: '967', label: 'Yemen'},
    {value: '260', label: 'Zambia'},
    {value: '263', label: 'Zimbabwe'},
]

const COUNTRY_CODE = [
    {value: 'US', label: 'United States', number: '1'},
    {value: 'KR', label: 'Korea, Republic of', number: '82'},
    {value: 'AF', label: 'Afghanistan', number: '93'},
    {value: 'AX', label: 'Aland Islands', number: '358'},
    {value: 'AL', label: 'Albania', number: '355'},
    {value: 'DZ', label: 'Algeria', number: '213'},
    {value: 'AS', label: 'American Samoa', number: '1-684'},
    {value: 'AD', label: 'Andorra', number: '376'},
    {value: 'AO', label: 'Angola', number: '244'},
    {value: 'AI', label: 'Anguilla', number: '1-264'},
    {value: 'AQ', label: 'Antarctica', number: '672'},
    {value: 'AG', label: 'Antigua and Barbuda', number: '1-268'},
    {value: 'AR', label: 'Argentina', number: '54'},
    {value: 'AM', label: 'Armenia', number: '374'},
    {value: 'AW', label: 'Aruba', number: '297'},
    {value: 'AU', label: 'Australia', number: '61'},
    {value: 'AT', label: 'Austria', number: '43'},
    {value: 'AZ', label: 'Azerbaijan', number: '994'},
    {value: 'BS', label: 'Bahamas', number: '1-242'},
    {value: 'BH', label: 'Bahrain', number: '973'},
    {value: 'BD', label: 'Bangladesh', number: '880'},
    {value: 'BB', label: 'Barbados', number: '1-246'},
    {value: 'BY', label: 'Belarus', number: '375'},
    {value: 'BE', label: 'Belgium', number: '32'},
    {value: 'BZ', label: 'Belize', number: '501'},
    {value: 'BJ', label: 'Benin', number: '229'},
    {value: 'BM', label: 'Bermuda', number: '1-441'},
    {value: 'BT', label: 'Bhutan', number: '975'},
    {value: 'BO', label: 'Bolivia, Plurinational State of', number: '591'},
    {value: 'BA', label: 'Bosnia and Herzegovina', number: '387'},
    {value: 'BW', label: 'Botswana', number: '267'},
    {value: 'BR', label: 'Brazil', number: '55'},
    {value: 'IO', label: 'British Indian Ocean Territory', number: '246'},
    {value: 'BN', label: 'Brunei Darussalam', number: '673'},
    {value: 'BG', label: 'Bulgaria', number: '359'},
    {value: 'BF', label: 'Burkina Faso', number: '226'},
    {value: 'BI', label: 'Burundi', number: '257'},
    {value: 'KH', label: 'Cambodia', number: '855'},
    {value: 'CM', label: 'Cameroon', number: '237'},
    {value: 'CA', label: 'Canada', number: '1'},
    {value: 'CV', label: 'Cape Verde', number: '238'},
    {value: 'KY', label: 'Cayman Islands', number: '1-345'},
    {value: 'CF', label: 'Central African Republic', number: '236'},
    {value: 'TD', label: 'Chad', number: '235'},
    {value: 'CL', label: 'Chile', number: '56'},
    {value: 'CN', label: 'China', number: '86'},
    {value: 'CX', label: 'Christmas Island', number: '61'},
    {value: 'CC', label: 'Cocos Islands', number: '61'},
    {value: 'CO', label: 'Colombia', number: '57'},
    {value: 'KM', label: 'Comoros', number: '269'},
    {value: 'CG', label: 'Congo', number: '242'},
    {value: 'CD', label: 'Congo, the Democratic Republic of the', number: '243'},
    {value: 'CK', label: 'Cook Islands', number: '682'},
    {value: 'CR', label: 'Costa Rica', number: '506'},
    {value: 'CI', label: "Cote d'Ivoire", number: '225'},
    {value: 'HR', label: 'Croatia', number: '385'},
    {value: 'CU', label: 'Cuba', number: '53'},
    {value: 'CW', label: 'Curacao', number: '599'},
    {value: 'CY', label: 'Cyprus', number: '357'},
    {value: 'CZ', label: 'Czech Republic', number: '420'},
    {value: 'DK', label: 'Denmark', number: '45'},
    {value: 'DJ', label: 'Djibouti', number: '253'},
    {value: 'DM', label: 'Dominica', number: '1-767'},
    {value: 'DO', label: 'Dominican Republic', number: '809'},
    {value: 'EC', label: 'Ecuador', number: '593'},
    {value: 'EG', label: 'Egypt', number: '20'},
    {value: 'SV', label: 'El Salvador', number: '503'},
    {value: 'GQ', label: 'Equatorial Guinea', number: '240'},
    {value: 'ER', label: 'Eritrea', number: '291'},
    {value: 'EE', label: 'Estonia', number: '372'},
    {value: 'ET', label: 'Ethiopia', number: '251'},
    {value: 'FK', label: 'Falkland Islands', number: '500'},
    {value: 'FO', label: 'Faroe Islands', number: '298'},
    {value: 'FJ', label: 'Fiji', number: '679'},
    {value: 'FI', label: 'Finland', number: '358'},
    {value: 'FR', label: 'France', number: '33'},
    {value: 'PF', label: 'French Polynesia', number: '689'},
    {value: 'GA', label: 'Gabon', number: '241'},
    {value: 'GM', label: 'Gambia', number: '220'},
    {value: 'GE', label: 'Georgia', number: '995'},
    {value: 'DE', label: 'Germany', number: '49'},
    {value: 'GH', label: 'Ghana', number: '233'},
    {value: 'GI', label: 'Gibraltar', number: '350'},
    {value: 'GR', label: 'Greece', number: '30'},
    {value: 'GL', label: 'Greenland', number: '299'},
    {value: 'GD', label: 'Grenada', number: '1-473'},
    {value: 'GP', label: 'Guadeloupe', number: '590'},
    {value: 'GU', label: 'Guam', number: '1-671'},
    {value: 'GT', label: 'Guatemala', number: '502'},
    {value: 'GG', label: 'Guernsey', number: '44-1481'},
    {value: 'GN', label: 'Guinea', number: '224'},
    {value: 'GW', label: 'Guinea-Bissau', number: '245'},
    {value: 'GY', label: 'Guyana', number: '592'},
    {value: 'HT', label: 'Haiti', number: '509'},
    {value: 'VA', label: 'Holy See {value: Vatican City State)', number: '379'},
    {value: 'HN', label: 'Honduras', number: '504'},
    {value: 'HK', label: 'Hong Kong', number: '852'},
    {value: 'HU', label: 'Hungary', number: '36'},
    {value: 'IS', label: 'Iceland', number: '354'},
    {value: 'IN', label: 'India', number: '91'},
    {value: 'ID', label: 'Indonesia', number: '62'},
    {value: 'IR', label: 'Iran, Islamic Republic of', number: '98'},
    {value: 'IQ', label: 'Iraq', number: '964'},
    {value: 'IE', label: 'Ireland', number: '353'},
    {value: 'IM', label: 'Isle of Man', number: '44-1624'},
    {value: 'IL', label: 'Israel', number: '972'},
    {value: 'IT', label: 'Italy', number: '39'},
    {value: 'JM', label: 'Jamaica', number: '1-876'},
    {value: 'JP', label: 'Japan', number: '81'},
    {value: 'JE', label: 'Jersey', number: '44-1534'},
    {value: 'JO', label: 'Jordan', number: '962'},
    {value: 'KZ', label: 'Kazakhstan', number: '7'},
    {value: 'KE', label: 'Kenya', number: '254'},
    {value: 'KI', label: 'Kiribati', number: '686'},
    {value: 'KP', label: "Korea, Democratic People's Republic of", number: '850'},
    {value: 'KW', label: 'Kuwait', number: '965'},
    {value: 'KG', label: 'Kyrgyzstan', number: '996'},
    {value: 'LA', label: "LAOS", number: '856'},
    {value: 'LV', label: 'Latvia', number: '371'},
    {value: 'LB', label: 'Lebanon', number: '961'},
    {value: 'LS', label: 'Lesotho', number: '266'},
    {value: 'LR', label: 'Liberia', number: '231'},
    {value: 'LY', label: 'Libya', number: '218'},
    {value: 'LI', label: 'Liechtenstein', number: '423'},
    {value: 'LT', label: 'Lithuania', number: '370'},
    {value: 'LU', label: 'Luxembourg', number: '352'},
    {value: 'MO', label: 'Macao', number: '853'},
    {value: 'MK', label: 'Macedonia', number: '389'},
    {value: 'MG', label: 'Madagascar', number: '261'},
    {value: 'MW', label: 'Malawi', number: '265'},
    {value: 'MY', label: 'Malaysia', number: '60'},
    {value: 'MV', label: 'Maldives', number: '960'},
    {value: 'ML', label: 'Mali', number: '223'},
    {value: 'MT', label: 'Malta', number: '356'},
    {value: 'MH', label: 'Marshall Islands', number: '692'},
    {value: 'MQ', label: 'Martinique', number: '596'},
    {value: 'MR', label: 'Mauritania', number: '222'},
    {value: 'MU', label: 'Mauritius', number: '230'},
    {value: 'YT', label: 'Mayotte', number: '262'},
    {value: 'MX', label: 'Mexico', number: '52'},
    {value: 'FM', label: 'Micronesia, Federated States of', number: '691'},
    {value: 'MD', label: 'Moldova, Republic of', number: '373'},
    {value: 'MC', label: 'Monaco', number: '377'},
    {value: 'MN', label: 'Mongolia', number: '976'},
    {value: 'ME', label: 'Montenegro', number: '382'},
    {value: 'MS', label: 'Montserrat', number: '1-664'},
    {value: 'MA', label: 'Morocco', number: '212'},
    {value: 'MZ', label: 'Mozambique', number: '258'},
    {value: 'MM', label: 'Myanmar', number: '95'},
    {value: 'NA', label: 'Namibia', number: '264'},
    {value: 'NR', label: 'Nauru', number: '674'},
    {value: 'NP', label: 'Nepal', number: '977'},
    {value: 'NL', label: 'Netherlands', number: '31'},
    {value: 'NC', label: 'New Caledonia', number: '687'},
    {value: 'NZ', label: 'New Zealand', number: '64'},
    {value: 'NI', label: 'Nicaragua', number: '505'},
    {value: 'NE', label: 'Niger', number: '227'},
    {value: 'NG', label: 'Nigeria', number: '234'},
    {value: 'NU', label: 'Niue', number: '683'},
    {value: 'NF', label: 'Norfolk Island', number: '672'},
    {value: 'MP', label: 'Northern Mariana Islands', number: '1-670'},
    {value: 'NO', label: 'Norway', number: '47'},
    {value: 'OM', label: 'Oman', number: '968'},
    {value: 'PK', label: 'Pakistan', number: '92'},
    {value: 'PW', label: 'Palau', number: '680'},
    {value: 'PS', label: 'Palestine, State of', number: '670'},
    {value: 'PA', label: 'Panama', number: '507'},
    {value: 'PG', label: 'Papua New Guinea', number: '675'},
    {value: 'PY', label: 'Paraguay', number: '595'},
    {value: 'PE', label: 'Peru', number: '51'},
    {value: 'PH', label: 'Philippines', number: '63'},
    {value: 'PN', label: 'Pitcairn', number: '64'},
    {value: 'PL', label: 'Poland', number: '48'},
    {value: 'PT', label: 'Portugal', number: '351'},
    {value: 'PR', label: 'Puerto Rico', number: '1-787'},
    {value: 'QA', label: 'Qatar', number: '974'},
    {value: 'RE', label: 'Reunion', number: '262'},
    {value: 'RO', label: 'Romania', number: '40'},
    {value: 'RU', label: 'Russia', number: '7'},
    {value: 'RW', label: 'Rwanda', number: '250'},
    {value: 'BL', label: 'Saint Barthelemy', number: '590'},
    {value: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha', number: '290'},
    {value: 'KN', label: 'Saint Kitts and Nevis', number: '1-869'},
    {value: 'LC', label: 'Saint Lucia', number: '1-758'},
    {value: 'MF', label: 'Saint Martin', number: '590'},
    {value: 'PM', label: 'Saint Pierre and Miquelon', number: '508'},
    {value: 'VC', label: 'Saint Vincent and the Grenadines', number: '1-784'},
    {value: 'WS', label: 'Samoa', number: '685'},
    {value: 'SM', label: 'San Marino', number: '378'},
    {value: 'ST', label: 'Sao Tome and Principe', number: '239'},
    {value: 'SA', label: 'Saudi Arabia', number: '966'},
    {value: 'SN', label: 'Senegal', number: '221'},
    {value: 'RS', label: 'Serbia', number: '381'},
    {value: 'SC', label: 'Seychelles', number: '248'},
    {value: 'SL', label: 'Sierra Leone', number: '232'},
    {value: 'SG', label: 'Singapore', number: '65'},
    {value: 'SX', label: 'Sint Maarten', number: '1-721'},
    {value: 'SK', label: 'Slovakia', number: '421'},
    {value: 'SI', label: 'Slovenia', number: '386'},
    {value: 'SB', label: 'Solomon Islands', number: '677'},
    {value: 'SO', label: 'Somalia', number: '252'},
    {value: 'ZA', label: 'South Africa', number: '27'},
    {value: 'GS', label: 'South Georgia and the South Sandwich Islands', number: '500'},
    {value: 'SS', label: 'South Sudan', number: '211'},
    {value: 'ES', label: 'Spain', number: '34'},
    {value: 'LK', label: 'Sri Lanka', number: '94'},
    {value: 'SD', label: 'Sudan', number: '249'},
    {value: 'SR', label: 'Suriname', number: '597'},
    {value: 'SJ', label: 'Svalbard and Jan Mayen', number: '47'},
    {value: 'SZ', label: 'Swaziland', number: '268'},
    {value: 'SE', label: 'Sweden', number: '46'},
    {value: 'CH', label: 'Switzerland', number: '41'},
    {value: 'SY', label: 'Syrian Arab Republic', number: '963'},
    {value: 'TW', label: 'Taiwan, Province of China', number: '886'},
    {value: 'TJ', label: 'Tajikistan', number: '992'},
    {value: 'TZ', label: 'Tanzania, United Republic of', number: '255'},
    {value: 'TH', label: 'Thailand', number: '66'},
    {value: 'TL', label: 'Timor-Leste', number: '670'},
    {value: 'TG', label: 'Togo', number: '228'},
    {value: 'TK', label: 'Tokelau', number: '690'},
    {value: 'TO', label: 'Tonga', number: '676'},
    {value: 'TT', label: 'Trinidad and Tobago', number: '1-868'},
    {value: 'TN', label: 'Tunisia', number: '216'},
    {value: 'TR', label: 'Turkey', number: '90'},
    {value: 'TM', label: 'Turkmenistan', number: '993'},
    {value: 'TC', label: 'Turks and Caicos Islands', number: '1-649'},
    {value: 'TV', label: 'Tuvalu', number: '688'},
    {value: 'UG', label: 'Uganda', number: '256'},
    {value: 'UA', label: 'Ukraine', number: '380'},
    {value: 'AE', label: 'United Arab Emirates', number: '971'},
    {value: 'GB', label: 'United Kingdom', number: '44'},
    {value: 'UM', label: 'United States Minor Outlying Islands', number: '246'},
    {value: 'UY', label: 'Uruguay', number: '598'},
    {value: 'UZ', label: 'Uzbekistan', number: '998'},
    {value: 'VU', label: 'Vanuatu', number: '678'},
    {value: 'VE', label: 'Venezuela, Bolivarian Republic of', number: '58'},
    {value: 'VN', label: 'Vietnam', number: '84'},
    {value: 'VG', label: 'Virgin Islands, British', number: '1284'},
    {value: 'VI', label: 'Virgin Islands, U.S.', number: '1'},
    {value: 'WF', label: 'Wallis and Futuna', number: '681'},
    {value: 'EH', label: 'Western Sahara', number: '212'},
    {value: 'YE', label: 'Yemen', number: '967'},
    {value: 'ZM', label: 'Zambia', number: '260'},
    {value: 'ZW', label: 'Zimbabwe', number: '263'},
]

export { COUNTRY_NUMBER, COUNTRY_CODE }