# Generated by Django 2.2.6 on 2019-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
    ]
