# Generated by Django 2.2.6 on 2019-11-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_confirm', 'Request Confirm'), ('request_cancel', 'Request Cancel')], max_length=100, verbose_name='Notification Type'),
        ),
    ]
