# Generated by Django 2.2.6 on 2019-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191121_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='responded',
            field=models.BooleanField(default=False, verbose_name='Re Dating Responded'),
        ),
    ]
