# Generated by Django 2.2.6 on 2019-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_views',
            field=models.BooleanField(default=False, verbose_name='Is Viewd'),
        ),
    ]
