# Generated by Django 2.2.6 on 2019-12-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_is_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_views',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Is Viewed'),
        ),
    ]
