# Generated by Django 2.2.6 on 2019-11-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20191127_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographeraccount',
            name='number',
        ),
        migrations.AddField(
            model_name='photographeraccount',
            name='content',
            field=models.CharField(default='default', max_length=255, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
