# Generated by Django 2.2.6 on 2019-12-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_auto_20191201_1519'),
        ('payment', '0003_auto_20191127_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='How much in dollars')),
                ('name', models.CharField(max_length=255, verbose_name='Deposant')),
                ('created_at', models.DateTimeField(verbose_name='Deposit Created At')),
                ('paid_at', models.DateTimeField(verbose_name='Deposit Completed At')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Order')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposit',
                'ordering': ['-id'],
            },
        ),
    ]
