# Generated by Django 2.2.6 on 2019-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deposit Created At'),
        ),
    ]
