# Generated by Django 2.2.6 on 2019-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20191201_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deposit Completed At'),
        ),
    ]
