# Generated by Django 2.2.6 on 2020-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20191201_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographeraccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
    ]
