# Generated by Django 2.2.6 on 2020-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_photographeraccount_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographeraccount',
            name='bank_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Code'),
        ),
    ]
